---
- name: Base CentOS 8 configuration
  hosts: all
  vars:
    sshd_port: 2048
    sshd_fw_port: "2048/tcp"
    github_keys: https://github.com/joelfreemanxyz.keys

  remote_user: ansible
  become: true

  tasks:
    - name: Install base packages
      yum:
        name:
          - epel-release
          - gpg
          - tmux
          - sudo
          - wget
          - firewalld
          
    - name: Create a user for Ansible
      user:
        name: ansible
        shell: /bin/bash
        groups: wheel
        append: yes

    - name: Make sure ansible user has my ssh keys added to it
      authorized_key:
        user: ansible
        state: present
        key: "{{ github_keys }}"

    - name: Make sure selinux is enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: Setup firewalld
      block:
        - service:
            name: firewalld
            state: started
            enabled: true
        - ansible.posix.firewalld:
            zone: public
            permanent: yes
            state: enabled
        - ansible.posix.firewalld:
            port: "{{ sshd_fw_port }}"
            permanent: yes
            state: enabled    

    - name: Update sshd config
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
      notify:
        - update selinux ssh port
        - restart sshd
        - disable port 22 ssh

    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted

  handlers:
    - name: update selinux ssh port
      command:
        cmd: semanage port -a -t ssh_port_t -p tcp "{{ sshd_port }}"
    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: disable port 22 ssh
      ansible.posix.firewalld:
            service: ssh
            permanent: yes
            state: disabled
