---
- name: Base CentOS 8 configuration
  hosts: vpn
  vars:
    sshd_port: 2048
    github_keys: https://github.com/joelfreemanxyz.keys

  remote_user: ansible
  become_method: sudo
  become: true

  tasks:
    - name: "Check port {{ ansible_port }}"
      wait_for:
        port: "{{ ansible_port }}"
        state: "started"
        host: "{{ inventory_hostname }}"
        connect_timeout: "5"
        timeout: "5"
      delegate_to: "localhost"
      ignore_errors: "yes"
      register: ssh_port
      become: false

    - name: "Check port 22"
      wait_for:
        port: "22"
        state: "started"
        host: "{{ inventory_hostname }}"
        connect_timeout: "5"
        timeout: "5"
      delegate_to: "localhost"
      ignore_errors: "yes"
      register: ssh_port_default
      become: false
      when: 
        - ssh_port is defined 
        - ssh_port.state is undefined

    - name: Set SSH port to 22
      set_fact:
        ansible_port: "22"
      when: ssh_port_default.state is defined

    - name: Update sshd config
      ansible.builtin.template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart sshd

    - name: update selinux ssh port
      community.general.seport:
        ports: "{{ sshd_port }}"
        proto: "tcp"
        setype: "ssh_port_t"
        state: present

    - name: allow port 2048 ssh
      ansible.posix.firewalld:
       port: "{{ sshd_port }}/tcp"
       permanent: yes 
       state: enabled 

    - name: Ensure SSH is reloaded if need be
      meta: flush_handlers       
    
    - name: Install base packages
      ansible.builtin.yum:
        name:
          - epel-release
          - gpg
          - tmux
          - sudo
          - wget
          - firewalld
    - name: Update Packages
      ansible.builtin.yum:
        name: '*'
        state: latest
          
    - name: Create a user for Ansible
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        groups: ansible, adm, wheel
        append: no

    - name: Make sure google_sudoers file is removed
      ansible.builtin.file:
        path: /etc/sudoers.d/google_sudoers
        state: absent

    - name: Make sure ansible user has my ssh keys added to it
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ github_keys }}"

    - name: Make sure selinux is enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: Setup firewalld
      block:
        - ansible.builtin.service:
            name: firewalld
            state: started
            enabled: true
        - ansible.posix.firewalld:
            zone: public
            permanent: yes
            state: enabled

    - name: Restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted
        enabled: yes

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted


