---

- name: Setup Pritunl VPN
  hosts: vpn
  remote_user: ansible
  become: yes
  vars:
    vpn_port: 4200
    mongodb_uri: "mongodb://localhost:27017/pritunl"

  tasks:
  - name: Install EPEL & other packages
    ansible.builtin.yum:
      name:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - gpg
      state: present

  - name: Import RPM keys
    ansible.builtin.shell:
      cmd: |
        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A;
        gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A > key.tmp; sudo rpm --import key.tmp; rm -f key.tmp
    
  - name: Setup MongoDB
    block:
      - name: Add mongodb repo
        ansible.builtin.template:
          src: templates/mongodb-org-4.2.repo
          dest: /etc/yum.repos.d/mongodb-org-4.2.repo

      - name: Install mongodb
        ansible.builtin.yum:
          name: mongodb-org
          state: present

      - name: Enable and start mongodb
        ansible.builtin.service:
          name: mongod
          state: started
          enabled: yes
      
      - name: Copy mongodb-backup systemd unit
        ansible.builtin.copy:
          src: templates/mongodb-backup.service
          dest: /etc/systemd/system/
          mode: '0600'
          owner: root
          group: root
          
      - name: Copy mongodb-backup systemd timer
        ansible.builtin.copy:
          src: templates/mongodb-backup.timer
          dest: /etc/systemd/system/
          owner: root
          group: root
          mode: '0600'

      - name: Copy mongodb backup script
        ansible.builtin.copy:
          src: templates/mongodb-backup.sh
          dest: /usr/local/bin/mongodb-backup
          mode: '0755'
          owner: root
          group: root

      - name: Enable mongodb-backup systemd timer
        ansible.builtin.systemd:
          name: mongodb-backup.timer
          state: started
          enabled: yes

      
  - name: Configure firewalld
    block:
      - ansible.posix.firewalld:
          service: https
          state: enabled
          permanent: yes

      - ansible.posix.firewalld:
          service: http
          state: enabled
          permanent: yes

      - ansible.posix.firewalld:
          port: "{{ vpn_port }}/udp"
          state: enabled
          permanent: yes