---

- name: Install EPEL & other packages
  ansible.builtin.package:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - gpg
    state: present

- name: Import RPM keys
  ansible.builtin.shell:
    cmd: |
      gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A;
      gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A > key.tmp; sudo rpm --import key.tmp; rm -f key.tmp
  

- name: Add mongodb repo
  ansible.builtin.copy:
    src: files/mongodb-org-4.2.repo
    dest: /etc/yum.repos.d/mongodb-org-4.2.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: Enable and start mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes


# Reccomended to use EBS backups instead.
- name: Configure Automatic MongoDB Backups to S3
  when: configure_mongodb_backups
  block:
  - name: Copy mongodb-backup systemd unit
    ansible.builtin.copy:
      src: templates/mongodb-backup.service
      dest: /etc/systemd/system/
      mode: '0600'
      owner: root
      group: root
      
  - name: Copy mongodb-backup systemd timer
    ansible.builtin.copy:
      src: templates/mongodb-backup.timer
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: '0600'

  - name: Copy mongodb backup script
    ansible.builtin.copy:
      src: templates/mongodb-backup.sh
      dest: /usr/local/bin/mongodb-backup
      mode: '0755'
      owner: root
      group: root

  - name: Enable mongodb-backup systemd timer
    ansible.builtin.systemd:
      name: mongodb-backup.timer
      state: started
      enabled: yes