---
- name: Add pritunl repo
  ansible.builtin.template:
    src: files/pritunl.repo
    dest: /etc/yum.repos.d/pritunl.repo

- name: Add Oracle EPEL 7 Repo ()
  block:
    - name: Download RPM keys
      ansible.builtin.get_url:
        url: https://yum.oracle.com/RPM-GPG-KEY-oracle-ol7
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
        mode: '0644'

    - name: Deploy temp oracle repo
      ansible.builtin.copy:
        src: files/oracle_epel7.repo
        dest: /etc/yum.repos.d/ol7-temp.repo

    - name: Install package
      ansible.builtin.package:
        name: oraclelinux-release-el7
        state: present

    - name: Remove temp repo
      ansible.builtin.file:
        path: /etc/yum.repos.d/ol7-temp.repo
        state: absent

- name: Install pritunl
  ansible.builtin.yum:
    name: 
      - pritunl
      - https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/getPackage/openvpn-2.4.10-1.el7.x86_64.rpm
    state: present

- name: Enable and start service
  ansible.builtin.service:
    name: pritunl
    state: started
    enabled: yes

- name: Update open file limits
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    block: |
      * hard nofile 64000
      * soft nofile 64000
      root hard nofile 64000
      root soft nofile 64000

- name: Configure Pritunl URI
  ansible.builtin.shell:
    cmd: pritunl set-mongodb {{ mongodb_uri }}
  run_once: true

- name: Configure Pritunl Web UI port
  ansible.builtin.shell:
    cmd: pritunl set app.server_port {{ pritunl_web_port }}