---
- name: Deploy SSHD config
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config 
    mode: 0644
    owner: root
    group: root

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded
