---

- name: Install and configure Pritunl VPN
  hosts: all
  # remote_user is ignored by packer, set for when running manually.
  remote_user: jfreeman
  become_method: sudo
  become: true
  vars_files:
    - vault.yml
  vars:
    - setup_firwalld: no
    - configure_mongodb_backups: no
    - ansible_become_password: "{{ vault_ansible_user_password }}"
  roles:
    - './jfreeman-pritunl/'