---
- name: Setup base configuration and install Pritunl
  hosts: all
  remote_user: ec2-user
  become_method: sudo
  become: true
  vars_files:
    - vault.yml
  vars:
    # vault_redhat_org_id, vault_redhat_activation_key and ansible_user_pasword are in vault
    github_keys: https://github.com/jxeldotdev.keys
    ansible_user_name: jfreeman
    setup_automatic_updates: yes
  roles:
    - role: './jfreeman-secure/'
    - role: './jfreeman-pritunl/'
      setup_firewalld: no
      configure_mongodb_backups: no
      ansible_become_password: "{{ vault_ansible_user_password }}"

