name: Build AWS AMI 
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-aws-ami:
    runs-on: ubuntu-latest
    container: 
      image: joelfreeman/ansible-packer-boto3:latest
      options: --user root
    steps:      
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_BRANCH }}
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 1200
          aws-region: ap-southeast-2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/packer-rhel8-pritunl.pkr.hcl

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: |
            -color=false 
            -on-error=abort 
            -var "vault_pw_file_path=./scripts/get_vault_pw.py"
            -var "vault_path=./ansible/vault.yml"
            -var ami_users='["${{ secrets.PROD_AWS_ACCOUNT_ID }}"]'
          target: packer/packer-rhel8-pritunl.pkr.hcl
        env:
          PACKER_LOG: 1

