name: Build AWS AMI 
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-aws-ami:
    runs-on: ubuntu-latest
    steps:      
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Ansible
        run: pip install ansible
      - name: Install boto3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 1200
          aws-region: ap-southeast-2
      
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./packer/packer-rhel8-pritunl.pkr.hcl
      - name: Build Artifact
      
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: |
            -var "vault_pw_file_path=./scripts/get_vault_pw.py"
            -var "vault_path=./ansible/vault.yml"
            -var 'ami_users=[${{ secrets.PROD_AWS_ACCOUNT_ID }}]'
          target: ./packer/packer-rhel8-pritunl.pkr.hcl
        env:
          PACKER_LOG: 1
