name: Build AWS AMI 
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          echo "TODO THIS IS NOT IMPLEMENTED YET!" 2>&1
          exit 255
    
  build-aws-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Pull Ansible Vault and Vault Password from Secrets Manager.
      - name: Pull Ansible Vault from AWS Secrets Manager 
        run: |
          vaultFileData=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.vault_file_arn }} | jq '.SecretBlob')
          if ! (echo $vaultFileData | base64 -d > ansible/vault.yaml);
            echo "Failed to decrypt Ansible Vault File." 2>&1
            exit 1
          fi
        
      - name: Pull Ansible Vault Password from AWS Secrets Manager
        run: |
          vaultFilePassword=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.vault_password_arn }} | jq '.SecretString' )
          if ! (echo $vaultFilePassword > ansible/vault-password); then
            echo "Unable to write Ansible Vault password to file." 2>&1
            exit 1
          fi

      - name: Build AWS AMI for Pritunl VM Image
        run: |
          echo "TODO THIS IS NOT IMPLEMENTED YET!" 2>&1
          exit 255

