name: Build AWS AMI 
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          echo "TODO THIS IS NOT IMPLEMENTED YET!" 2>&1
          exit 255
  build-aws-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2
      
      - name: Build AWS AMI
        run: |
          packer 
      # - name: Build AWS AMI for Pritunl VM Image
      #   run: |
      #     echo "TODO" 2>&1
      #     exit 255
      #     # packer build \ 
      #     # -var vault_pw_file="/tmp/vault_pw_file" \
      #     # -var vault_path="/tmp/ansible_vault" \
      #     # packer/packer-rhel8-pritunl.pkr.hcl

