name: Build AWS AMI 
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-aws-ami:
    runs-on: ubuntu-latest
    container: 
      image: joelfreeman/ansible-packer-boto3:latest
      options: --user root
    steps:      
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_BRANCH }}
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 2100
          aws-region: ap-southeast-2
      
      - name: Build AWS AMI for Pritunl VM Image
        env:
          VAULT_AWS_SECRET_NAME: ${{ secrets.VAULT_AWS_SECRET_NAME }}
        run: |
          GIT_REF=$(git rev-parse --short HEAD)
          packer build -var "git_ref=${GIT_REF}" -var "subnet_id=${{ secrets.PACKER_SUBNET_ID }}" -var "vault_pw_file_path=./scripts/get_vault_pw.py" -var "vault_path=./ansible/vault.yml" -var 'ami_users=[${{ secrets.AMI_ACCOUNTS }}]' ./packer/packer-rhel8-pritunl.pkr.hcl
        shell: bash

